"""create_all_tables

Revision ID: 57457049ad56
Revises: 
Create Date: 2026-04-02 23:53:34.584586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57457049ad56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('planId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('roofArea', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('billFile', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('planId')
    )
    op.create_index(op.f('ix_plans_planId'), 'plans', ['planId'], unique=False)
    op.create_index(op.f('ix_plans_userId'), 'plans', ['userId'], unique=False)
    op.create_table('consumption_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('planId', sa.String(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('totalAmount', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_data_planId'), 'consumption_data', ['planId'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('planId', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solar', sa.Float(), nullable=True),
    sa.Column('batterySOC', sa.Float(), nullable=True),
    sa.Column('gridCost', sa.Float(), nullable=True),
    sa.Column('gridImport', sa.Float(), nullable=True),
    sa.Column('gridExport', sa.Float(), nullable=True),
    sa.Column('consumption', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_planId'), 'predictions', ['planId'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('planId', sa.String(), nullable=False),
    sa.Column('solarSize', sa.Float(), nullable=True),
    sa.Column('batterySize', sa.Float(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('saving', sa.Float(), nullable=True),
    sa.Column('totalCost', sa.Float(), nullable=True),
    sa.Column('paybackPeriod', sa.Float(), nullable=True),
    sa.Column('annualGeneration', sa.Float(), nullable=True),
    sa.Column('co2Reduction', sa.Float(), nullable=True),
    sa.Column('graphData', sa.JSON(), nullable=True),
    sa.Column('rawOutput', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planId'], ['plans.planId'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_planId'), 'results', ['planId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_planId'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_predictions_planId'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_consumption_data_planId'), table_name='consumption_data')
    op.drop_table('consumption_data')
    op.drop_index(op.f('ix_plans_userId'), table_name='plans')
    op.drop_index(op.f('ix_plans_planId'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
